name: Trend-Micro-Container-Security-for-CI-CD


on: 
  push:
    branches: 
      - master

jobs:
    Build_and_Push:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          # Container Build
          - name: Container Build
            run : docker build -t myapp:latest .
          # Container Push
          - name: DockerHub Login
            run: docker login --username felipecosta09 --password ${{ secrets.DOCKERHUB }}
          - name: Tag Docker Image
            run: docker tag myapp felipecosta09/myapp:latest
          - name: Push Docker Images to DockerHub
            run: docker push felipecosta09/myapp:latest
    Container_Scan:
       runs-on: ubuntu-latest
       needs: [Build_and_Push]
       steps:
         # Container Scan
         - name: Cloud One Container Scan DockerHub
           uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@1.0.1
           with:
              DSSC_IMAGE_NAME: felipecosta09/myapp:latest
              DSSC_SMARTCHECK_HOST: a65d597b6a3f911ea80860ee2b859e57-1778246550.us-east-1.elb.amazonaws.com
              DSSC_SMARTCHECK_USER: administrator
              DSSC_SMARTCHECK_PASSWORD: 3b5963b4f46297cff9980753eac0d0
              DSSC_IMAGE_PULL_AUTH: '{"username": "felipecosta09","password": "${{ secrets.DOCKERHUB }}"}'
              DSSC_FINDINGS_THRESHOLD: '{"malware": 10, "vulnerabilities": { "defcon1": 10, "critical": 10, "high": 10 }, "contents": { "defcon1": 10, "critical": 10, "high": 10 }, "checklists": { "defcon1": 10, "critical": 10, "high": 10 }}'
              DSSC_INSECURE_SKIP_TLS_VERIFY: true
              DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: true
