name: Trend-Micro-Container-Security-for-CI-CD


on: 
  push:
    branches: 
      - master

jobs:
    Build_and_Push:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          # Container Build
          - name: Container Build
            run : docker build -t myapp:latest .
          # Container Push
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION: us-east-1
          - name: Tag Docker Image
            run: docker tag myapp:latest 650143975734.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
          - name: Push Docker Images to DockerHub
            run: docker push 650143975734.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
    Container_Scan:
       runs-on: ubuntu-latest
       needs: [Build_and_Push]
       steps:
         # Container Scan
         - name: Cloud One Container Scan in AWS ECR
           uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@1.0.2
           with:
              DSSC_IMAGE_NAME: 650143975734.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
              DSSC_SMARTCHECK_HOST: ${{ secrets.DSSC_SMARTCHECK_HOST }}
              DSSC_SMARTCHECK_USER: ${{ secrets.DSSC_SMARTCHECK_USER }}
              DSSC_SMARTCHECK_PASSWORD: ${{ secrets.DSSC_SMARTCHECK_PASSWORD }}
              DSSC_IMAGE_PULL_AUTH: ${{ secrets.DSSC_IMAGE_PULL_AUTH }}
              DSSC_FINDINGS_THRESHOLD: ${{ secrets.DSSC_FINDINGS_THRESHOLD }}
              DSSC_INSECURE_SKIP_TLS_VERIFY: true
              DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: true
